### ISSUE TITLE
Cannot compile due to lack of files to bootstrap bbutils.pas and bbutilsh.inc

### ISSUE THREAD

**Issue by gcarreno** [benibela/internettools#10]
Hi there,

First I tried with the current HEAD version and found out there is no `bbutilsh.inc`, so I dug around and found the `*_generate` programs.

Not even after downloading the VideLibri 1.71, that contains a `bbutils_template.pas`, I could bootstrap: `__safemove__()` is nowhere to be found.

Is there something I'm missing?

Many thanks in advance for any help!

Cheers,
Gus

**Comment by benibela** [comment]
I forgot to included that file in the list of public files. 

But here is another mirror: https://github.com/benibela/bbutils

**Comment by gcarreno** [comment]
Thanks!!

Are you going to leave that one in ?

You can't really compile any of the *.lpk's without that file and probably others from bbutils.

Cheers!!
Gus

**Comment by gcarreno** [comment]
Hey Benito,

Well, I tried again and now I'm clashing with a fcl-stl/ghashmap issue:
__ghashmap.pp(129,49) Error: Only class methods, class properties and class variables can be referred with class references__ 
But that's related to FPC itself, but still odd since it should be tested code...

Dunno if related to the fact that I had to use `USE_SOROKINS_REGEX` instead of `USE_FLRE`, cuz I don't have that regex lib.

Any idea where I can get the *FLRE* regex lib? I'm always looking for a good regex lib ;)

Cheers,
Gus

**Comment by benibela** [comment]
>Are you going to leave that one in ?

It takes a while to update. If I push now, it will upload other untested changes.

>ghashmap.pp(129,49) Error: Only class methods, class properties and class variables can be referred with class references

Seems I initialized the generics there wrong. 

Really better to use it with FLRE
 
>Any idea where I can get the FLRE regex lib?

For now here: http://github.com/benibela/flre

**Comment by gcarreno** [comment]
> It takes a while to update. If I push now, it will upload other untested changes.

Are you updating this from the mercurial repo?

> Seems I initialized the generics there wrong.

Humm, good to know that this is an error with generics. With the error showing up on the declaration of the generics you're using it can really throw you off!!

> For now here: http://github.com/benibela/flre

Man, why didn't I check there first ARGHHHH?!?!?!

Thanks!! I'll add that to the pile and try and recompile it again.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Benito,

YAY \o/ !! Finally got it to compile.

I think you should give people a bit of a howto on the README to avoid further issues like this.

Never the less, MANY, many thanks for all your assistance!!!

Cheers,
Gus

**Comment by benibela** [comment]
>Are you updating this from the mercurial repo?

I have one huge private mercurial repository containing all projects. Then the other repositories are created by picking a list of files from it.

>I think you should give people a bit of a howto on the README to avoid further issues like this. 

The zip archive on my webpage has all the files

**Comment by gcarreno** [comment]
> The zip archive on my webpage has all the files

Cool, then you should add something in the README pointing at that fact so you don't get issues like mine so often :)
