### ISSUE TITLE
Please help with this memory leak.

### ISSUE THREAD

**Issue by murnur19** [benibela/internettools#12]
If I execute evaluate using thread I always get this heaptrc.
[Project1.trc.txt](https://github.com/benibela/internettools/files/853660/Project1.trc.txt)

This heaptrc doens't appear if I run it with main thread.
Thanks.

**Comment by benibela** [comment]
Do you call `xquery.freeThreadVars` at the end of the thread?

**Comment by riderkick** [comment]
It's still there.
Can you please take a look at this example.
[project1.tar.gz](https://github.com/benibela/internettools/files/854249/project1.tar.gz)

**Comment by murnur19** [comment]
It's still there.
Can you please take a look at this example.
[Uploading project1.tar.gz…]()

**Comment by benibela** [comment]
That is an interesting situation.

fpc creates a temporary IXQValue variable to store the result of evaluate/the for loop, which is released at the end of the execute function.

You need to call free on the query engine after that variable has been released, i.e. have the calculation and free in different methods.

freeThreadVars was for the global query function and IXQValue.map method.  If you create and free a query engine, it has no effect right now.

That still leaves two unexplained, unfreed blocks

**Comment by murnur19** [comment]
So, what you suggest. I want to reuse the engine for multiple xpath query from a thread.

**Comment by benibela** [comment]
>So, what you suggest. I want to reuse the engine for multiple xpath query from a thread.

Create one engine at the beginning of the thread and free it at the end of the execute method. But do not do any calculations involving IXQValues inside the execute method.

When there are no calculations/ixqvalues in the execute method, you  could put `TXQueryEngine.create.free;` there. The last free in a thread frees everything, except  still existing ixqvalues.

I could add  a test to free the interfaces immediately, if no engine exists. But it would make things slower. All this caching memory management is an optimization for people having millions of IXQValues. 

>That still leaves two unexplained, unfreed blocks

That seems to be the lack of freeonterminate := true; in the example.

**Comment by murnur19** [comment]
Can you make an example?
I would like to handle the download by myself, examine a page source and probably spawn another thread to examine the sub page. While also running multiple thread with similar job. So there will be a lot of engine and IXQValues.
> That seems to be the lack of freeonterminate := true; in the example.
Yes, I forgot that.

**Comment by benibela** [comment]
Just keep the IXQValue away from execute:

```
  TXPath3Thread=class(tthread)
  private
    engine: TXQueryEngine;
    procedure addoutput;
    procedure addout(const s: string);
  protected
    procedure Calculate;
    procedure Execute; override;
  end;

procedure TXPath3Thread.Calculate;
var
  v: IXQValue;
  t: TTreeParser;
begin
  t:=TTreeParser.create;
  try
    t.parsingModel := pmHTML;
    t.repairMissingStartTags:=true;
    t.repairMissingEndTags:=true;
    t.parseTree('<html><a href="a"/></html>');
    for v in engine.evaluateXPath3('//a/@href',t.getLastTree) do
      addout(v.toString);
  except
    on e:exception do
      addout(e.Message);
  end;
  t.free
end;

procedure TXPath3Thread.Execute;
begin
  engine := TXQueryEngine.create;
  Calculate;
  engine.free;
  FreeOnTerminate := true;
end;
```

Or with the global engine:

```
  TXPath3Thread=class(tthread)
  private
    procedure addoutput;
    procedure addout(const s: string);
  protected
    procedure Calculate;
    procedure Execute; override;
  end;

procedure TXPath3Thread.Calculate;
var
  v: IXQValue;
  t: TTreeParser;
begin
  t:=TTreeParser.create;
  try
    t.parsingModel := pmHTML;
    t.repairMissingStartTags:=true;
    t.repairMissingEndTags:=true;
    t.parseTree('<html><a href="a"/></html>');
    for v in xqvalue(t.getLastTree).map('//a/@href') do
      addout(v.toString);
  except
    on e:exception do
      addout(e.Message);
  end;
  t.free
end;

procedure TXPath3Thread.Execute;
begin
  Calculate;
  freeThreadVars;
  FreeOnTerminate := true;
end;
                    
```

**Comment by murnur19** [comment]
Do the global engine thread-safe?

**Comment by benibela** [comment]
yes.

(and that is the reason for the memory issues. Every thread gets its own cache, and when the thread ends without freeing the entire cache, no other thread can access the cache to free or use it)

**Comment by murnur19** [comment]
I see. Thanks.
