### ISSUE TITLE
Invalid symbol in hex entity: xxx

### ISSUE THREAD

**Issue by murnur19** [benibela/internettools#14]
Failed when trying to parse this page.

```
**** Retrieving (GET): http://www.nirsoft.net/utils/htmlastext.html ****
**** Processing: http://www.nirsoft.net/utils/htmlastext.html ****
An unhandled exception occurred at $004222B4:
Exception: Invalid symbol in hex entity: xxx;)

  $004222B4
  $00423297
  $004A2E21
  $004A2BAB
  $004A2A50
  $004A99DE
  $00513404
  $00435575
  $004321E8
  $00431408
  $00430ECE
  $0043B2A2
```

**Comment by benibela** [comment]
fixed in d637e0f19c2952e47396fbd7d8f26a2f161e1c1e

not yet production ready. 

the commit also sets an encoding for the returned strings, which enabled fpc's new automatic encoding conversion, which could change things anywhere the string is used. 

and there are some other (outdated) entity issues
