### ISSUE TITLE
Memory leaks with fpc trunk?

### ISSUE THREAD

**Issue by murnur19** [benibela/internettools#15]
When using fpc trunk. This simple code produce a memory leaks.
`query('doc("https://www.google.com")//a/@href').toString`
```
Call trace for block $0649FEE0 size 32
  $00560DAF  TXQVALUENODE__CREATE,  line 1709 of ./data/xquery_types.inc
  $0056B438  TXQVLIST__ADD,  line 5742 of ./data/xquery.pas
  $00570FAA  TXQUERYENGINE__EXPANDSEQUENCE,  line 7557 of ./data/xquery.pas
  $005517A6  TXQTERMPATH__EVALUATE,  line 2930 of ./data/xquery_terms.inc
  $00543D3E  TXQUERY__EVALUATE,  line 4952 of ./data/xquery.pas
  $00543C72  TXQUERY__EVALUATE,  line 4941 of ./data/xquery.pas
  $0056DB71  TXQUERYENGINE__EVALUATE,  line 6675 of ./data/xquery.pas
  $0056DD19  TXQUERYENGINE__EVALUATEXQUERY3,  line 6725 of ./data/xquery.pas
```

[project1.trc.txt](https://github.com/benibela/internettools/files/1256186/project1.trc.txt)

This is not happen with fpc 3.0.2. I'm not sure where to look at. Maybe an fpc bug. Not sure what to report.

**Comment by benibela** [comment]
They might have caused that with revision 36757. Can you try fpc 36756?

**Comment by murnur19** [comment]
That's seems to be the case. No leaks on 36756. Can you please report it to mantis?

**Comment by benibela** [comment]
here https://bugs.freepascal.org/view.php?id=32353

Their commit is correct, but it clashes with my optimizations
