### ISSUE TITLE
Infinity memory consumption

### ISSUE THREAD

**Issue by SergeyPyankov** [benibela/internettools#16]
I use latest Lazarus 1.8.2 with FPC 3.0.4 on Windows and create simple test application with the one button:
```
unit Unit1;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, FileUtil, Forms, Controls, Graphics, Dialogs, StdCtrls;

type
  TForm1 = class(TForm)
    Button1: TButton;
    procedure Button1Click(Sender: TObject);
  end;

var
  Form1: TForm1;

implementation

{$R *.lfm}

uses
  simpleinternet;

procedure TForm1.Button1Click(Sender: TObject);
var
  S: string;
begin
  S := process('https://github.com/benibela/internettools', '//div[1]').toString;
end;

end.
```
After _each button click app increases the memory consumption by about 1 Mb_, i. e. 50 clicks lead to +45 Mb.

**Comment by benibela** [comment]
There is  no garbage collection for documents yet

You  need to call `freeThreadVars` to free all that memory at once

**Comment by benibela** [comment]
With 98c621770702ca6651c95b089c1396c753140e66 all documents are reference counted

but now you need to be careful when using TTreeNode
