### ISSUE TITLE
Configuration proxy with username and password?

### ISSUE THREAD

**Issue by rkiggen** [benibela/internettools#17]
Hi,

I'm trying to scrape webpages which works quite good with the internettools package, however I haven't found out how I can use the application behind a proxy which requires a username and password.

Currently I just create a TInternetConfig record like so:
  internetConfig.useProxy := True;
  internetConfig.proxyHTTPName := '192.168.56.10';
  internetConfig.proxyHTTPPort := '80';

And next I tell the internetaccess package to use the above settings, like so:
internetaccess.defaultInternetConfiguration := internetConfig;

The TInterConfig however doesn't provide me with the options to specify an username or a password.

Is that possible at all or not, and if so can you tell me how to accomplish this?

Kind regards,
Rob

**Comment by benibela** [comment]
you can try it with 30e99dffb49ea7a9b0f8210acd788b9e79f6dd7d
