### ISSUE TITLE
Multi Header

### ISSUE THREAD

**Issue by Gerom** [benibela/internettools#2]
Hello,
I think there was an error if you use multiple header

__unit w32internetaccess;__

__function TW32InternetAccess.doTransferRec__
....
HttpAddRequestHeadersA(hfile, 
__pchar(additionalHeaders), length(additionalHeaders[i]),__ 
HTTP_ADDREQ_FLAG_REPLACE or HTTP_ADDREQ_FLAG_ADD)

*i use this code :*
HttpAddRequestHeadersA(hfile,
__PChar(additionalHeaders[i]+#13#10#0), dword(-1),__
HTTP_ADDREQ_FLAG_REPLACE OR HTTP_ADDREQ_FLAG_ADD)

**Comment by benibela** [comment]
Such a silly mistake.

But isn't it enough to change it `PChar(additionalHeaders[i])` ? I do not think the line break is needed when adding only a single header
