### ISSUE TITLE
Can I query from a string?

### ISSUE THREAD

**Issue by TangMonk** [benibela/internettools#20]
```
 uses xquery;
writeln(query('doc("<html>......html strings....</html>")//title').toString);
```

**Comment by benibela** [comment]
yes, you need to replace `doc` with `parse-xml` or `parse-html`

**Comment by TangMonk** [comment]
I am using process() to archived, thanks!

**Comment by TangMonk** [comment]
Hi, those function seems not appears on document

**Comment by benibela** [comment]
What document? Here is a longer [function list](http://www.benibela.de/documentation/internettools/xpath-functions.html)

**Comment by TangMonk** [comment]
Thanks , it is useful!
