### ISSUE TITLE
Compiling on FreeBSD

### ISSUE THREAD

**Issue by sprock** [benibela/internettools#23]
Hello,
Compiling as part of xidel.  I'm getting this on FreeBSD 11.3:

-- Building...
Free Pascal Compiler version 3.2.0 [2020/06/14] for x86_64
Copyright (c) 1993-2020 by Florian Klaempfl and others
Target OS: FreeBSD for x86-64
Compiling xidel.pas
Compiling ./internettools/internet/multipagetemplate.pas
Compiling ./internettools/data/extendedhtmlparser.pas
Compiling ./internettools/data/simplehtmltreeparser.pas
Compiling ./internettools/data/simplehtmlparser.pas
Compiling ./internettools/data/htmlinformation.pas
Compiling ./internettools/data/simplehtmltreeparser.pas
Compiling ./internettools/data/xquery.pas
Compiling ./internettools/data/xquery__functions.pas
Compiling ./internettools/data/xquery.pas
Compiling ./internettools/data/xquery__parse.pas
Compiling ./internettools/data/bbutilsbeta.pas
bbutilsbeta.pas(140,5) Error: Record type expected
bbutilsbeta.pas(151,1) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted

I know nothing about pascal else I'd investigate further.
Cheers,
Roger

**Comment by benibela** [comment]
You can try it with cebb431

**Comment by sprock** [comment]
Hello,

Benito van der Zander <notifications@github.com> writes:

> You can try it with cebb431
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you.  That got past the error and downloading FLRE and rcmdline
got past a couple of others but now I'm stuck again:

xidelbase.pas(3736,20) Warning: Symbol "SetCommandLine" is deprecated
Compiling ./internettools/internet/synapseinternetaccess.pas
synapseinternetaccess.pas(42,3) Fatal: Can't find unit httpsend used by synapseinternetaccess

I poked about but could not find httpsend on-line.

Thanks,
Roger

**Comment by sprock** [comment]
Benito van der Zander <notifications@github.com> writes:

> You can try it with cebb431

OK, fortget my last message I found httpsend in synapse and xidel is now
compiled.

Thanks for your help.
