### ISSUE TITLE
Failed to compile, cause  Error: Incompatible type for arg no. 2

### ISSUE THREAD

**Issue by radiaku** [benibela/internettools#27]
Hello, I got this error when failed to compile?

`xquery__regex.pas(696,70) Error: Incompatible type for arg no. 2: Got "<procedure variable type of function(const PChar;const TFLRECaptures):AnsiString(0) of object;Register>", expected "<procedure variable type of function(const PChar;const LongInt;const TFLRECaptures):AnsiString(0) of object;Register>"`

**Comment by benibela** [comment]
You could use the flre from two weeks ago until this is figured out

**Comment by radiaku** [comment]
Thanks, its working.
