### ISSUE TITLE
declaration of TFLRESizeInt

### ISSUE THREAD

**Issue by piula** [benibela/internettools#30]
Hello,

according to Google, you're the only one to use the type ``TFLRESizeInt``, but I cannot see where it is declared. It's being used in xquery__regex.pas -- does this compile for you?

**Comment by benibela** [comment]
Then Google is lying. It is from FLRE: https://github.com/BeRo1985/flre

**Comment by piula** [comment]
Ah, great. Thank you!

**Comment by nunu6689** [comment]
Keep getting email notif even tho my email wasn't registered. Weird. I just register it a minute ago to see if it goes away. There's nothing in "github.com/watching".
