### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by TrueHouse** [benibela/internettools#31]
Hi, I get this error when trying to compile internettools:

xquery__regex.pas(696,70) Error: Incompatible type for arg no. 2: Got "<procedure variable type of function(const PChar;const LongInt;const TFLRECaptures):AnsiString of object;Register>", expected "<procedure variable type of function(const PChar;const TFLRECaptures):AnsiString of object;Register>"

Seems to be the same issue that someone else reported. You answered that they should use the old FLRE. Where do I get that?

Thank you.

**Comment by benibela** [comment]
No, your message is exactly the opposite

You appear to have the old FLRE

But since I fixed the other issue, it now only works with the new FLRE
