### ISSUE TITLE
Failed to compile to x86_64 due to recent fpc changes

### ISSUE THREAD

**Issue by murnur19** [benibela/internettools#4]
The error message just about incompatible variable.
[internettools.data.patch.txt](https://github.com/benibela/internettools/files/179919/internettools.data.patch.txt)

**Comment by benibela** [comment]
I see, revision 33246

But I will have to implement it differently to work with older fpc as well.

And I was thinking about changing it to virtual methods, instead raw functions pointer anyways. The XQuery Test Suite has some weird string comparison functions with different sorting parameters

**Comment by murnur19** [comment]
Great, looking forward to it.

**Comment by benibela** [comment]
should be fixed in 34b756b3923e73d2eae60d428249ebbb530522e8
