### ISSUE TITLE
MimeType

### ISSUE THREAD

**Issue by kajzersoze** [benibela/internettools#6]
Hello,
In Synapse I define MimeType like this :
```
hsend : THTTPSend;
hsend.MimeType := 'application/x-www-form-urlencoded';
```
Trying to figure out how to do that here with httpRequest using synapseinternetaccess, tried few things but no luck. Any tips ?

**Comment by zbyna** [comment]
Hi,
try something like:
```pascal 
defaultInternet.additionalHeaders.Text:= 'Content-Type: application/x-www-form-urlencoded';
```
or
```pascal
defaultInternet.contentTypeForData:= 'application/x-www-form-urlencoded';
```
see: http://www.benibela.de/documentation/internettools/internetaccess.TInternetAccess.html#additionalHeaders

**Comment by kajzersoze** [comment]
Tried both, still doesn't work.

**Comment by benibela** [comment]
Are you sending some data as 2nd parameter to httpRequest? The one-argument function only sends GET requests and with GET the content type is ignored. For the 2-argument version, urlencoded is actually the default content type

**Comment by kajzersoze** [comment]
Yes I am, and I have 2nd argument, that all works fine when there is no need for 'application/x-www-form-urlencoded' 
But when there is a need for 'application/x-www-form-urlencoded' it works the same way as with Synapse without hsend.MimeType := 'application/x-www-form-urlencoded';

**Comment by benibela** [comment]
Why is there a need?

Perhaps something else is wrong

**Comment by kajzersoze** [comment]
When you send data with more pairs separated by & then there's a need.
For example :
username=foo&password=bar

So, if you send just username=foo then there's no need for 'application/x-www-form-urlencoded' , but if you send username=foo&password=bar then there's a need.

Nothing else is wrong :)

**Comment by kajzersoze** [comment]
Maybe if I give you example it would be clearer what the problem is.
This is using synapse unit :
```
procedure TForm1.Button1Click(Sender: TObject);
var
  hsend : THTTPSend;
  res : string;
  obj: ISuperObject;
begin
  hsend:=THTTPSend.Create;
  hsend.MimeType := 'application/x-www-form-urlencoded';
  WriteStrToStream(hsend.Document,'username=whatever');

  hsend.HTTPMethod('POST', 'https://steamcommunity.com/login/getrsakey/');

  obj := TSuperObject.ParseStream(hsend.Document, true);
  res := obj.AsString;
  memo1.lines.add(res);
end;  
```
Using superobject here for json parser but you can replace it with any other parser.
Now, you don't need to change username and bother with that, just live it as it is and run the code.
When you run it you will see something like this :
`{"success":true,"token_gid":"a45581039c52a5c","timestamp":"562165850000","publickey_mod":"B80E1A6F0D54B4643D7872A57FA04CC1E3C9AF5345E813CA9FB01E35188175745189B1B49CEDE084AF1ED7DE99E178771999CEA2CC5F6D2D60EE32FAD3CE5BE6A0A4E0BBA6D38375463889A05688CCAF748DE24521857240460783519D82B556597FE78969292C0B3948D569B2E44F4C5D99EE41B07E771B3356448E72DBF83AB783945E8B3FA733C5E650D20F3D506AB7AC525D54DF2B1D982D6F2D6DA2CF281D3B9740AC62DDE7D041ADC044F3D94A53E3E5F5E336FA0966815C25EAE93B3B7362BDD5D81E5019737D7E2346AC32C0140D1E80BC98A9510CAD62C65D377540D03FCEB4C4F612614B29C1605CE194AFD97CC1683B50AF8282AE738122ED15AB","publickey_exp":"010001"}
`

Now, if you remove or comment this line :   hsend.MimeType := 'application/x-www-form-urlencoded';
you will see this result : {"success":false}
And that's all I get by using internet tools, no matter what I try.
Okay, so if you can get "{"success":true....."  by using synapseinternetaccess that would be great and I would love to see how you did that.

**Comment by kajzersoze** [comment]
So, by using synapseinternetaccess like this it works actually, but I'll get back to you with the problem later.

```
procedure TForm1.Button1Click(Sender: TObject);
var
 LoginData : TStringlist;
 res : string;
 obj: ISuperObject;
begin
 LoginData := TStringList.Create;
 LoginData.Add('username=whatever');
 res := httpRequest('https://steamcommunity.com/login/getrsakey/', LoginData);
 memo1.lines.add(res);
 LoginData.Free;
end;      
```

**Comment by kajzersoze** [comment]
Actually it works, sorry about this, it was my mistake !
