### ISSUE TITLE
Compile Internettool in lazarus

### ISSUE THREAD

**Issue by TehBotolSosro** [benibela/internettools#9]
hi,

I'm trying to compile internettools in lazarus version 1.7 FPC 3.1.1 SVN: 52808 but got the following error

xquery__regex.pas(47,23) Fatal: Cannot find FLRE used by xquery__regex of package internettools.

i already download FLRE from https://github.com/benibela/flre/ but i don't know how to install it or use it in my lazarus windows

i'm new in lazarus so help me please thanks

**Comment by benibela** [comment]
You need to download FLRE. 

It comes from there: https://github.com/BeRo1985/flre/

Unfortunately that version does not seem to compile with fpc, so you better get it from here: https://github.com/benibela/flre/

Or you can disable FLRE and enable Sorokin instead, but then some  function won't work with Unicode: https://github.com/benibela/internettools/blob/master/data/xquery__regex.pas#L28-L33

**Comment by benibela** [comment]
I now include FLRE in the occasional zip file releases
